---
name: Mahesh Build and publish the image from reusable repo

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'


jobs:

  steps:
  
    -
      name: asas
      build-and-test:
        permissions:
          id-token: write # need this for OIDC
          contents: read
        uses: https://github.com/shboddu/poetry-test/blob/master/.github/GitHub-ci2.yaml@master
        with:
          run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" > $GITHUB_ENV
        secrets: inherit
