---
name: Mahesh Build and publish the image from reusable repo

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'


jobs:

  steps:

    uses: https://github.com/subhash403/github-reusable/blob/main/.github/workflows/github-cr.yaml@main
    with:
      run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" > $GITHUB_ENV
    secrets: inherit
