---
name: Mahesh Build and publish the image from reusable repo

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'


jobs:

  steps:
  
    -
      name: Get tag
      id: repository
  #   run: echo "tag=$(git describe --tags HEAD)" > $GITHUB_ENV
      run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" > $GITHUB_ENV
    -
      name: asas
      build-and-test:
        permissions:
          id-token: write # need this for OIDC
          contents: read
        uses: https://github.com/subhash403/github-reusable/blob/main/.github/workflows/github-cr.yaml@master
        with:
          run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" > $GITHUB_ENV
        secrets: inherit
